### ISSUE TITLE
Illogical validation

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/vatnumber#10]
It is possible to register an address with a valid VAT number from another country.
![Screenshot_20230308_120340](https://user-images.githubusercontent.com/20421361/223699087-7ed6b0a3-7ec6-4c9d-aaea-6ca3d14cf3cd.png)

**Comment by getdatakick** [comment]
Fixed by commits a71f626ed9e4d67c8f85669a35635468455e2da8 and 2d06068a2eaa463916f5efc53fb58522fff5a41e
