### ISSUE TITLE
No possibility to add a national VAT number

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/vatnumber#12]
In many countries, national VAT number is different from EU VAT number and does not contain a prefix.
Currently, you cannot add an address with such a national VAT number. And without a VAT number, you cannot issue an invoice.
That's why there was a condition in my modification to exclude VAT number for 'VATNUMBER_COUNTRY' from validation.

**Comment by getdatakick** [comment]
Well, then we have bigger issue here.

First of all, there was a bug in your changes. Basically, you overrode the previous validation -- result of webservice call to VIES was ignored, and replaced with result of prefix/country validation check.

```php
            // At this point, $result may contain error message that is overwritten by following code

            if ($excludedCountry != $address->id_country && $isoAddress != $isoIntracom) {
                $result = Tools::displayError('VAT number inconsistent with country.');
            } else {
                $result = true; 
             }                      
```

After I fixed this, the check for excluded country was meaningless, because the VIES always reported internal vat numbers as invalid. This database contains only cross-border vat numbers.

Now the question is what to do with this. 

Maybe don't do any validation for excluded country?

**Comment by getdatakick** [comment]
Or maybe have completely different validations for cross-border transactions and for intra-country transactions, maybe even country specific

**Comment by e-com-presta** [comment]
In my opinion, validating EU VAT number for domestic sales doesn't make sense, because sales are always with VAT anyway.
And probably in many countries national VAT numbers are different from EU VAT numbers. This is the case in Germany and Poland, for example. Companies with a national VAT number are not required to have an EU VAT number.
On other hand, implementing validation of national VAT numbers would be a huge job. You would have to integrate 27 different tax institutions.
For Polish stores, I do validation using API of Polish Ministry of Finance.
Example: https://wl-api.mf.gov.pl/api/search/nip/6783096366?date=2023-03-13

**Comment by getdatakick** [comment]
> in my opinion, validating EU VAT number for domestic sales doesn't make sense, because sales are always with VAT anyway.

In my country I have to file monthly tax return that includes VAT# for all sales over some threshold. If the vat# does not exists, it is automatically rejected by tax office. Tax number validation would help me tremendously in this area.

But I agree that it's too much work. 

Let's disable the validation for national VAT numbers. Maybe prepare some ground work for country-specific validation, in case somebody would like to implement it for their own countries.

**Comment by e-com-presta** [comment]
Due to the fact that VIES server is working tragically, I do it this way in my clients' stores.
On frontoffice, validation is disabled, and in order panel, semi-automatic validation is available either on VIES server or on Polish Ministry of Finance server.
Maybe this solution will appeal to you and is worth implementing?
Google Maps is best to be completely discarded from thirty bees core, and in place of map make a hook on which validation modules already made for a specific country could work.
![2023-03-13_13-10](https://user-images.githubusercontent.com/20421361/224795222-a3a0723a-80cb-49f6-86aa-b06ae567d620.png)
