### ISSUE TITLE
Italy additional needs

### ISSUE THREAD

**Issue by CasualRascal** [thirtybees/vatnumber#6]
Italy has been enforcing electronic invoices since 2019. "Electronic" does not mean pdf or html, but is the name given to them from this whole system that is in place. 

Automating these invoices is a hard task and goes beyond the scope of this module. Instead, providing enough information to the shop owner so that he can handle them manually is in the scope of this module.

If the shop is based in italy, additional things must be required by italian B2B customers:

- PEC 
- Codice Destinatario

Both should be asked. If none is given by the customer, then the electronic invoice that the shop owner has to manually send to the Sistema di Interscambio will be unable to be delivered to the customer. The customer should be warned that if neither PEC not Codice Destinatario are provided, the electronic invoice will be available on the website of Agenzia delle Entrate in the Fatture & Corrispettivi section.

Furthermore, the invoice generated by thirty bees needs to include a disclaimer stating that the invoice has no value but it is just a courtesy invoice, the electronic invoice is being sent to the Sistema di Interscambio and the courtesy invoice number does not match the electronic invoice number.

P.S. what solutions are in place to prevent IP bans when exceeding rate limits?

**Comment by getdatakick** [comment]
I don't see why this should be implemented as part of VAT module. 

The purpose of this module is to issue invoice with zero VAT tax, but only if the customer can provide EU VAT number that is usable for **cross-border** transaction.

If there are other requirements for invoicing within Italy, it is totally out of the scope of this module, in my opinion.

**Comment by CasualRascal** [comment]
Understood, I thought this module would be meant to be also usable for within-border transactions as it does implement EU VAT numbers evaluation correctly and VAT numbers are still required within-border for B2B transactions.

If within-border transactions are not in the scope of this module, I will proceed with forking and extending it.

Thank you for the hard work on the thirty bees project.
